### ISSUE TITLE
Loader needed

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/harshgoel05.github.io#8]
Need to add a beautiful loader matching with the theme ( orange color and black background)

**Comment by charchithere** [comment]
Hello! I want to work on this

**Comment by harshgoel05** [comment]
Hey @charchithere go ahead. Assigning to you! :)

**Comment by agatharejina** [comment]
hi!! May I contribute?

**Comment by charchithere** [comment]
Thanks @harshgoel05 i am working on this

**Comment by harshgoel05** [comment]
Hey @charchithere are you still working on it?

**Comment by charchithere** [comment]
@harshgoel05 yes

**Comment by charchithere** [comment]
@harshgoel05 Just facing some issues. Preloader is not fading / main page is not loading .

**Comment by GagandeepSingh0115** [comment]
I would like to work on it.

**Comment by GagandeepSingh0115** [comment]
@harshgoel05 please assign this task to me

**Comment by harshgoel05** [comment]
@charchithere and @GagandeepSingh0115 you both can try on this. Just raise a PR once done 🗡️
