### ISSUE TITLE
add Technologies to project section

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/harshgoel05.github.io#9]
need to add a technologies paragraph (emphasized with span) for each project.

Just add it to one for testing the design

![image](https://user-images.githubusercontent.com/48649088/94782432-d376b400-03e8-11eb-967c-5df404d1c32e.png)

Somewhere below the paragraph of kzilla.xyz like  TECH STACK: HTML, CSS, SVELTE, NODEJS

**Comment by Ironheartcoder** [comment]
hello sir , 
I would like to work on this :>
it'll be really kind of u .... if u can assign this to me :)

**Comment by harshgoel05** [comment]
Here you go! @Ironheartcoder

**Comment by prabhu4444** [comment]
Hi, I'd like to contribute to this issue, if it still there I would like to work on it?

**Comment by harshgoel05** [comment]
Hey @Ironheartcoder are you working on it? Please confirm else I need to assign it to someone else.

Thanks!

**Comment by Rajdeepc** [comment]
@harshgoel05 Can work on this if no one is working
